- type: antag
  id: BloodCultist
  name: roles-antag-blood-cultist-name
  antagonist: true
  setPreference: true
  objective: roles-antag-blood-cultist-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 43200

- type: startingGear
  id: BloodCultistGear
  storage:
    back:
    - RitualDagger
    - RunedMetal20

# Traitors
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodCultist
  name: "Роль Культиста Крові"
#  description: mind-role-traitor-description
  components:
  - type: MindRole
    antagPrototype: BloodCultist
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: BloodCultistRole
