- type: entity
  name: "агент синдикатського флоту"
  abstract: true
  parent:
  - MobHumanoidHostileBase
  - MobHumanoidInvetory
  - MobHumanoidHostileAISimpleRanged
  id: MobSyndicateNavalBase
  components:
  - type: Body
    prototype: HumanSyntheticOrgans # New set of synthetic organs grants faster removal of toxins from bloodstream
    requiredLegs: 2
  - type: NpcFactionMember
    factions:
    - Syndicate
  #- type: AutoImplant
    #implants:
    #- DeathRattleImplant
    #- DeathAcidifierImplant
    #- MicroBombImplant
  - type: RechargeBasicEntityAmmo
    rechargeCooldown: 1
    rechargeSound:
      path: /Audio/_NF/Effects/silence.ogg
  # - type: AutoWakeUp

# Humans
# Syndicate Captain, "armed" with AP Python
- type: entity
  name: "капітан синдикату"
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalCaptainA
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalCaptainGearA
    - type: RechargeBasicEntityAmmo
      rechargeCooldown: 0.75
      rechargeSound:
        path: /Audio/_NF/Effects/silence.ogg
    - type: BasicEntityAmmoProvider
      proto: BulletMagnumAP
      capacity: 1
      count: 1
    - type: Gun
      showExamineText: false
      fireRate: 0.75
      selectedMode: SemiAuto
      availableModes:
      - SemiAuto
      soundGunshot: /Audio/Weapons/Guns/Gunshots/revolver.ogg

- type: entity
  parent: MobSyndicateNavalCaptainA
  id: MobSyndicateNavalCaptainB
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalCaptainGearB
    - type: BasicEntityAmmoProvider
      proto: BulletMagnum
      capacity: 1
      count: 1

- type: entity
  parent: MobSyndicateNavalCaptainA
  id: MobSyndicateNavalCaptainC
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalCaptainGearC
    - type: BasicEntityAmmoProvider
      proto: BulletMagnum
      capacity: 1
      count: 1

- type: entity
  parent: MobSyndicateNavalCaptainA
  id: MobSyndicateNavalCaptainD
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalCaptainGearD
    - type: BasicEntityAmmoProvider
      proto: BulletMagnum
      capacity: 1
      count: 1

# Syndicate Engineer, "armed" with shotgun
- type: entity
  name: "інженер синдикату"
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalEngineerA
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalEngineerGearA
    - type: RechargeBasicEntityAmmo
      rechargeCooldown: 2
      rechargeSound:
        path: /Audio/_NF/Effects/silence.ogg
    - type: BasicEntityAmmoProvider
      proto: ShellShotgunSlug
      capacity: 1
      count: 1
    - type: Gun
      showExamineText: false
      fireRate: 2
      selectedMode: SemiAuto
      availableModes:
      - SemiAuto
      soundGunshot: /Audio/Weapons/Guns/Gunshots/shotgun.ogg

- type: entity
  parent: MobSyndicateNavalEngineerA
  id: MobSyndicateNavalEngineerB
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalEngineerGearB
    - type: BasicEntityAmmoProvider
      proto: ShellShotgun
      capacity: 1
      count: 1

- type: entity
  parent: MobSyndicateNavalEngineerB
  id: MobSyndicateNavalEngineerC
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalEngineerGearC

- type: entity
  parent: MobSyndicateNavalEngineerB
  id: MobSyndicateNavalEngineerD
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalEngineerGearD
    - type: BasicEntityAmmoProvider
      proto: PelletShotgunBeanbag
      capacity: 1
      count: 1

# Syndicate "Medic", throws poisoned darts laced with 2u of Impedrezene (hallucinogenic, deals minor poison damage, makes you barf and slows you down)
# Look for darts here: /Resources/Prototypes/_NF/Entities/Objects/Weapons/Throwable/throwable_weapons.yml
- type: entity
  name: "медик синдикату"
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalMedicA
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalMedicGearA
    - type: RechargeBasicEntityAmmo
      rechargeCooldown: 2
      rechargeSound:
        path: /Audio/_NF/Effects/silence.ogg
    - type: Gun
      showExamineText: false
      fireRate: 4
      selectedMode: SemiAuto
      availableModes:
      - SemiAuto
      soundGunshot:
        collection: BulletMiss

- type: entity
  parent: MobSyndicateNavalMedicA
  id: MobSyndicateNavalMedicB
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalMedicGearB

- type: entity
  parent: MobSyndicateNavalMedicA
  id: MobSyndicateNavalMedicC
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalMedicGearB

- type: entity
  parent: MobSyndicateNavalMedicA
  id: MobSyndicateNavalMedicD
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalMedicGearD

# Second Officer, "armed" with Advanced Laser Pistol
- type: entity
  name: "другий офіцер синдикату"
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalSecondOfficerA
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalSecondOfficerGearA
    - type: HitscanBatteryAmmoProvider
      proto: RedMediumLaser
      fireCost: 100
    - type: BatterySelfRecharger
      autoRecharge: true
      autoRechargeRate: 50
    - type: Battery
      maxCharge: 600
      startingCharge: 600
    - type: Gun
      showExamineText: false
      fireRate: 1
      selectedMode: SemiAuto
      availableModes:
        - SemiAuto
      soundGunshot: /Audio/Weapons/Guns/Gunshots/laser_cannon.ogg

- type: entity
  parent: MobSyndicateNavalSecondOfficerA
  id: MobSyndicateNavalSecondOfficerB
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalSecondOfficerGearB

- type: entity
  parent: MobSyndicateNavalSecondOfficerA
  id: MobSyndicateNavalSecondOfficerC
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalSecondOfficerGearC

- type: entity
  parent: MobSyndicateNavalSecondOfficerA
  id: MobSyndicateNavalSecondOfficerD
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalSecondOfficerGearD
    - type: HitscanBatteryAmmoProvider
      proto: RedLaser
      fireCost: 50

# Syndicate Security Operative, "armed" with Atreides SMG
- type: entity
  name: "оперативник синдикату"
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalOperatorA
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalOperatorGearA
    - type: RechargeBasicEntityAmmo
      rechargeCooldown: 1.5
      rechargeSound:
        path: /Audio/_NF/Effects/silence.ogg
    - type: BasicEntityAmmoProvider
      proto: BulletPistol
      capacity: 8
      count: 8
    - type: Gun
      showExamineText: false
      minAngle: 10
      maxAngle: 30
      fireRate: 8
      angleIncrease: 3
      angleDecay: 6
      selectedMode: FullAuto
      availableModes:
        - FullAuto
      soundGunshot: /Audio/Weapons/Guns/Gunshots/smg.ogg

- type: entity
  parent: MobSyndicateNavalOperatorA
  id: MobSyndicateNavalOperatorB
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalOperatorGearB

- type: entity
  parent: MobSyndicateNavalOperatorA
  id: MobSyndicateNavalOperatorC
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalOperatorGearC

- type: entity
  parent: MobSyndicateNavalOperatorA
  id: MobSyndicateNavalOperatorD
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalOperatorGearD

# Syndicate Grenadier, "armed" with china lake
- type: entity
  name: "гренадер синдикату"
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalGrenadierA
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalGrenadierGearA
    - type: RechargeBasicEntityAmmo
      rechargeCooldown: 5
      rechargeSound:
        path: /Audio/_NF/Effects/silence.ogg
    - type: BasicEntityAmmoProvider
      proto: GrenadeFrag
      capacity: 1
      count: 1
    - type: Gun
      showExamineText: false
      fireRate: 1
      selectedMode: SemiAuto
      availableModes:
        - SemiAuto
      soundGunshot: /Audio/Weapons/Guns/Gunshots/grenade_launcher.ogg

- type: entity
  parent: MobSyndicateNavalGrenadierA
  id: MobSyndicateNavalGrenadierB
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalGrenadierGearB
    - type: BasicEntityAmmoProvider
      proto: GrenadeBlast
      capacity: 1
      count: 1

- type: entity
  parent: MobSyndicateNavalGrenadierA
  id: MobSyndicateNavalGrenadierC
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalGrenadierGearC
    - type: BasicEntityAmmoProvider
      proto: GrenadeBaton
      capacity: 1
      count: 1

- type: entity
  parent: MobSyndicateNavalGrenadierA
  id: MobSyndicateNavalGrenadierD
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalGrenadierGearD
    - type: BasicEntityAmmoProvider
      proto: GrenadeFlash
      capacity: 2
      count: 2

# Syndicate Saboteur, "armed" with EMP Viper
- type: entity
  name: "диверсант синдикату"
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalSaboteurA
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalSaboteurGearA
    - type: RechargeBasicEntityAmmo
      rechargeCooldown: 1
      rechargeSound:
        path: /Audio/_NF/Effects/silence.ogg
    - type: Gun
      showExamineText: false
      fireRate: 6
      selectedMode: FullAuto
      availableModes:
      - FullAuto
      soundGunshot: /Audio/Weapons/Guns/Gunshots/pistol.ogg

- type: entity
  parent: MobSyndicateNavalSaboteurA
  id: MobSyndicateNavalSaboteurB
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalSaboteurGearB

- type: entity
  parent: MobSyndicateNavalSaboteurA
  id: MobSyndicateNavalSaboteurC
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalSaboteurGearC

- type: entity
  parent: MobSyndicateNavalSaboteurA
  id: MobSyndicateNavalSaboteurD
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalSaboteurGearD

# Hostile Victim of Experimentation, "armed" with shiv
- type: entity
  name: "полонений"
  parent:
  - MobHumanoidHostileBase
  - MobHumanoidHostileAISimpleMelee
  id: MobExperimentationVictim
  components:
    - type: NameIdentifier
      group: GenericNumber
    - type: NpcFactionMember
      factions:
        - SimpleHostile
    - type: Loadout
      prototypes:
        - SyndicateVictimInsaneGear
    - type: InputMover
    - type: MobMover
    - type: HTN
      rootTask:
        task: SimpleHumanoidHostileCompound

# Syndicate Commander, "armed" with AK
- type: entity
  name: "командир синдикату" # Mega Fauna for Dungeons
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalCommanderA
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalCommanderGearA
    - type: Stamina
      critThreshold: 500 # Extra hard to incapacitate and loot
    - type: AutoImplant
      implants:
      - DeathRattleImplant
    - type: RechargeBasicEntityAmmo
      rechargeCooldown: 1.5
      rechargeSound:
        path: /Audio/_NF/Effects/silence.ogg
    - type: BasicEntityAmmoProvider
      proto: CartridgeLightRifle
      capacity: 4
      count: 4
    - type: Gun
      showExamineText: false
      fireRate: 5
      selectedMode: SemiAuto
      availableModes:
      - SemiAuto
      soundGunshot: /Audio/Weapons/Guns/Gunshots/rifle2.ogg

- type: entity
  parent: MobSyndicateNavalCommanderA
  id: MobSyndicateNavalCommanderB
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalCommanderGearB
    - type: BasicEntityAmmoProvider
      proto: CartridgeRifle
      capacity: 4
      count: 4
    - type: Gun
      showExamineText: false
      fireRate: 5
      selectedMode: SemiAuto
      availableModes:
      - SemiAuto
      soundGunshot: /Audio/Weapons/Guns/Gunshots/ltrifle.ogg

- type: entity
  parent: MobSyndicateNavalCommanderB
  id: MobSyndicateNavalCommanderC
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalCommanderGearC

- type: entity
  parent: MobSyndicateNavalCommanderB
  id: MobSyndicateNavalCommanderD
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalCommanderGearD

# Syndicate Deckhand, "armed" with Viper
- type: entity
  name: "матрос синдикату"
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalDeckhandA
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalDeckhandGearA
    - type: RechargeBasicEntityAmmo
      rechargeCooldown: 1
      rechargeSound:
        path: /Audio/_NF/Effects/silence.ogg
    - type: BasicEntityAmmoProvider
      proto: BulletPistol
      capacity: 4
      count: 4
    - type: Gun
      showExamineText: false
      fireRate: 0.5
      selectedMode: FullAuto
      availableModes:
      - FullAuto
      soundGunshot: /Audio/Weapons/Guns/Gunshots/pistol.ogg

- type: entity
  parent: MobSyndicateNavalDeckhandA
  id: MobSyndicateNavalDeckhandB
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalDeckhandGearB

- type: entity
  parent: MobSyndicateNavalDeckhandA
  id: MobSyndicateNavalDeckhandC
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalDeckhandGearC

- type: entity
  parent: MobSyndicateNavalDeckhandA
  id: MobSyndicateNavalDeckhandD
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalDeckhandGearD

# Syndicate Mime, melee, "armed" with chainsaw
- type: entity
  name: "мім синдикату"
  parent:
  - MobSyndicateNavalBase
  - MobHumanoidHostileAISimpleMelee
  id: MobSyndicateNavalMime
  components:
    - type: Loadout
      prototypes:
        - SyndicateNavalMimeGear
    - type: Stamina
      critThreshold: 500
    - type: MovementSpeedModifier
      baseWalkSpeed: 4
      baseSprintSpeed: 6

# Syndicate Chemwarrior, shoots healthy mixes of chems
# Look for chems here: /Resources/Prototypes/_NF/Entities/Objects/Weapons/Ammunition/Projectiles/chem.yml
- type: entity
  name: "хімвоїн синдикату"
  parent: MobSyndicateNavalBase
  id: MobSyndicateNavalChemwarriorA
  components:
  - type: Loadout
    prototypes:
    - SyndicateNavalChemwarriorGearA
  - type: RechargeBasicEntityAmmo
    rechargeCooldown: 2
    rechargeSound:
      path: /Audio/_NF/Effects/silence.ogg
  - type: Gun
    showExamineText: false
    fireRate: 4
    selectedMode: SemiAuto
    availableModes:
    - SemiAuto
    soundGunshot: /Audio/Weapons/Guns/Gunshots/water_spray.ogg

- type: entity
  parent: MobSyndicateNavalChemwarriorA
  id: MobSyndicateNavalChemwarriorB
  components:
  - type: Loadout
    prototypes:
    - SyndicateNavalChemwarriorGearB

- type: entity
  parent: MobSyndicateNavalChemwarriorA
  id: MobSyndicateNavalChemwarriorC
  components:
  - type: Loadout
    prototypes:
    - SyndicateNavalChemwarriorGearC

- type: entity
  parent: MobSyndicateNavalChemwarriorA
  id: MobSyndicateNavalChemwarriorD
  components:
  - type: Loadout
    prototypes:
    - SyndicateNavalChemwarriorGearD
