- type: entity
  name: "коробка чисткогранат"
  parent: BoxCardboard
  id: BoxCleanerGrenades
  description: "Коробка, повна чисткогранат."
  components:
  - type: StorageFill
    contents:
      - id: CleanerGrenade
        amount: 4
  - type: Sprite
    layers:
      - state: box
      - state: flashbang
