- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLoneAbductor
  name: "Роль Самотнього Викрадача"
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: LoneAbductorAntag
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorVictim
  name: "Роль Жертви Викрадення"
  components:
  - type: MindRole
    antagPrototype: AbductorVictimAntag
  - type: AbductorVictim
