- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Box #50-∞
  - Atlas #5-20
  - Reach #0-7
  - Cluster #10-35
  - Arena #30-80
  - Aspid #0-70
  - Bagel #40-76
  - Asterisk #0-60
  - Train #10-50
  - Shoukou #0-60
  - Core #30-60
  - Edge #10-80
  - Fland #70-∞
  - Hammurabi #50-∞
  - Tortuga #50-∞
  - Packed #5-40
  - Pebble #0-30
  - Saltern #0-35
  - Omega #10-35
  - Lighthouse #15-55
  - Marathon #35-70
  - Meta #50-∞
  - Oasis #70-∞
  - TheHive #30-80
  - Origin #50-∞
  - Submarine #60-∞
  - Cog #35-70
