- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Theatre # DeltaV - Add Theatre access
  - Reporter # DeltaV - Add Reporter access
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 7200 #DeltaV 2 hours
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed

- type: startingGear
  id: ReporterGear
  subGear:
  - ReporterPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
    neck: JournalistCamera #PIRATE
  innerClothingSkirt: ClothingUniformJumpsuitJournalist
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
  storage: # DeltaV: Give reporters tape recording equipment
    back:
    - TapeRecorder
    - CassetteTape
    - CassetteTape

- type: startingGear
  id: ReporterPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitReporter
    head: ClothingHeadEnvirohelmReporter
    gloves: ClothingHandsGlovesEnviroglovesReporter
