- type: entity
  id: ThrusterSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: "плата двигуна служби безпеки"
  components:
  - type: MachineBoard
    prototype: ThrusterSecurity
    requirements:
      Capacitor: 3
    materialRequirements:
      Steel: 5

- type: entity
  id: ThrusterNfsdMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: "плата двигуна nfsd"
  components:
  - type: MachineBoard
    prototype: ThrusterNfsd
    requirements:
      Capacitor: 3
    materialRequirements:
      Steel: 5

- type: entity
  id: SmallThrusterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: "плата малого двигуна"
  components:
  - type: MachineBoard
    prototype: SmallThruster
    requirements:
      Capacitor: 4
    materialRequirements:
      Steel: 5
  - type: StaticPrice
    price: 12.5

# Gyroscope
- type: entity
  id: GyroscopeSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: "плата гіроскопа служби безпеки"
  components:
  - type: MachineBoard
    prototype: GyroscopeSecurity
    requirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2

- type: entity
  id: SmallGyroscopeSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: "плата малого гіроскопа служби безпеки"
  components:
  - type: MachineBoard
    prototype: SmallGyroscopeSecurity
    requirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2
  - type: StaticPrice
    price: 12.5

- type: entity
  id: GyroscopeNfsdMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: "плата гіроскопа nfsd"
  components:
  - type: MachineBoard
    prototype: GyroscopeNfsd
    requirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2

- type: entity
  id: SmallGyroscopeNfsdMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: "плата малого гіроскопа nfsd"
  components:
  - type: MachineBoard
    prototype: SmallGyroscopeNfsd
    requirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2
  - type: StaticPrice
    price: 12.5

- type: entity
  id: SmallGyroscopeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: "плата малого гіроскопа"
  components:
  - type: MachineBoard
    prototype: SmallGyroscope
    requirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2
  - type: StaticPrice
    price: 12.5
