- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-mag
  access:
  # - Service - DeltaV, removed from service department
  - Justice # DeltaV - Justice dept
  - Lawyer
  - Maintenance
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 18000 #Pirate 5 hrs
    - !type:CharacterDepartmentTimeRequirement # DeltaV - Security dept time requirement
      department: Security
      min: 14400 # 4 hours
    - !type:CharacterEmployerRequirement
      employers:
      - IdrisIncorporated
      - NanoTrasen
  special: # Goobstation - Everyone knows lawyers are soulless.
  - !type:AddComponentSpecial
    components:
    - type: Condemned
      soulOwnedNotDevil: true

- type: startingGear
  id: LawyerGear
  subGear:
  - LawyerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackLawyerFilled #DeltaV - stamp included
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetJustice # Pirate
    pocket1: BookSecurity
  inhand:
    - BriefcaseBrownFilled
    - BookSecurity # Pirate
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelLawyerFilled #DeltaV - stamp included
  duffelbag: ClothingBackpackDuffelLawyerFilled #DeltaV - stamp included

- type: startingGear
  id: LawyerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitEnviroslacks
    head: ClothingHeadEnvirohelmColorWhite
    gloves: ClothingHandsGlovesEnviroglovesWhite
