using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Pirate.ReactionChamber.UI;
[GenerateTypedNameReferences]
public sealed partial class ReactionChamberWindow : DefaultWindow
{

    public bool Active;
    public float Temp;
    public ReactionChamberWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SetActive(false);
    }
    public void SetTemp(float temp)
    {
        Temp = temp;
    }
    public void SetActive(bool active)
    {
        Active = active;
        ActiveButton.Pressed = active;

        if (active)
        {
            ActiveButton.Text = "Вимкнути";
        }
        else
        {
            ActiveButton.Text = "Увімкнути";
        }
    }

}
