using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Pirate.ReactionChamber.UI;
[GenerateTypedNameReferences]
public sealed partial class ReactionChamberWindow : DefaultWindow
{
    public ReactionChamberWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
