- type: entity
  id: CrateFishingGoodies
  parent: CratePlastic
  name: "ящик рибальських снастей"
  description: "Пара вудок, ведмідь та капелюх. Усе, що потрібно, щоб виловити всю рибу на станції!"
  components:
  - type: StorageFill
    contents:
      - id: FishingRod
      - id: FishingRodGoon
      - id: ClothingHeadFishCap
      - id: DrinkBeerBottleFull
